part of 'main_layout.dart';

class Images {
  static List<String> getImages(Locale locale) {
    switch (locale.languageCode) {
      case 'en':
        return _imagesEn;
        case 'tr':
        return _imagesTr;
        case 'de':
        return _imagesDe;
        case 'ar':
        return _imagesAr;
      default:
        return _imagesEn;
    }
  }

  static const List<String> _imagesAr = [
  'assets/screen_savers/ar/Allah1.jpg',
'assets/screen_savers/ar/Bedetu.jpg',
'assets/screen_savers/ar/Besmele4.jpg',
'assets/screen_savers/ar/Elhamdulillah-Ala.jpg',
'assets/screen_savers/ar/Euzubikelimatillahi.jpg',
'assets/screen_savers/ar/Felak.jpg',
'assets/screen_savers/ar/Felillahilhamd.jpg',
'assets/screen_savers/ar/Fesabruncemil.jpg',
'assets/screen_savers/ar/Fetih.jpg',
'assets/screen_savers/ar/Gaferallahu-Lena.jpg',
'assets/screen_savers/ar/Ilahi_Ente_Rabbi.jpg',
'assets/screen_savers/ar/Ve-Rabbeke-Fekebbir.jpg',
'assets/screen_savers/ar/Ve-Rahmeti-Vesiat.jpg',
'assets/screen_savers/ar/Ve-Zekkir.jpg',
'assets/screen_savers/ar/Vel-Hamdulillh.jpg',
'assets/screen_savers/ar/Vema-Tevfiki.jpg',
'assets/screen_savers/ar/Vemen-Yettekillahe.jpg',
'assets/screen_savers/ar/Ya-Men-Latifu-Lem.jpg',
'assets/screen_savers/ar/Ya-Muhavvil.jpg',
'assets/screen_savers/ar/Ya-Mukallib.jpg',
'assets/screen_savers/ar/Ya-Musarrif.jpg',
'assets/screen_savers/ar/Ya-Mustafa.jpg',
'assets/screen_savers/ar/Ya-Mutecelli.jpg',
'assets/screen_savers/ar/Ya-Rabbena-Tahhir.jpg',
];
  static const List<String> _imagesDe = ['assets/screen_savers/de/Koran 10-107.jpg',
'assets/screen_savers/de/Koran 3-150.jpg',
'assets/screen_savers/de/Koran 3-173.jpg',
'assets/screen_savers/de/Koran 49-11.jpg',
'assets/screen_savers/de/Koran 7_55.jpg',
'assets/screen_savers/de/Sprich gut.jpg',
'assets/screen_savers/de/Ya Allah, berichtige.jpg',
];

  static const List<String> _imagesTr = [
    'assets/screen_savers/tr/1-allah.jpg',
'assets/screen_savers/tr/2-rahman.jpg',
'assets/screen_savers/tr/3-rahim.jpg',
'assets/screen_savers/tr/4-melik.jpg',
'assets/screen_savers/tr/5-guddus.jpg',
'assets/screen_savers/tr/6-selam.jpg',
];

  // List of screen saver images
  static const List<String> _imagesEn = [
    'assets/screen_savers/us/Allah is Kind.jpg',
    'assets/screen_savers/us/AllahDoesNotOpen.jpg',
    'assets/screen_savers/us/Alvarli Lutfi.jpg',
    'assets/screen_savers/us/Bashfulness.jpg',
    'assets/screen_savers/us/Be humble.jpg',
    'assets/screen_savers/us/Chastity.JPG',
    'assets/screen_savers/us/DesiresMakeSlaves.jpg',
    'assets/screen_savers/us/Detachment from the world.jpg',
    'assets/screen_savers/us/DoNotOvereat.jpg',
    'assets/screen_savers/us/Exchange gifts.jpg',
    'assets/screen_savers/us/Forgive People.JPG',
    'assets/screen_savers/us/Gold-antique-mirror.jpg',
    'assets/screen_savers/us/He who pretends.JPG',
    'assets/screen_savers/us/Hold on to your salah-1.jpg',
    'assets/screen_savers/us/HonestySaves.jpg',
    'assets/screen_savers/us/Interest in others faults.jpg',
    'assets/screen_savers/us/Keep your.jpg',
    'assets/screen_savers/us/Most Dismal Home.jpg',
    'assets/screen_savers/us/Obstacle Stepping Stone.jpg',
    'assets/screen_savers/us/Piety dress.jpg',
    'assets/screen_savers/us/Praiseof People.JPG',
    'assets/screen_savers/us/Quran 12-87.jpg',
    'assets/screen_savers/us/Quran 16-53.jpg',
    'assets/screen_savers/us/Quran 2 153.jpg',
    'assets/screen_savers/us/Quran 23-118.jpg',
    'assets/screen_savers/us/Quran 26-183.jpg',
    'assets/screen_savers/us/Quran 3-173.jpg',
    'assets/screen_savers/us/Quran 31-17.jpg',
    'assets/screen_savers/us/Quran 4 147.jpg',
    'assets/screen_savers/us/Quran 5-105.jpg',
    'assets/screen_savers/us/Quran 6-152.jpg',
    'assets/screen_savers/us/Quran 65-2.jpg',
    'assets/screen_savers/us/Quran 7 126.jpg',
    'assets/screen_savers/us/Quran 7-199.jpg',
    'assets/screen_savers/us/Quran 7-204.jpg',
    'assets/screen_savers/us/Quran 7_55.jpg',
    'assets/screen_savers/us/Quran 94-6.jpg',
    'assets/screen_savers/us/Raise your words.jpg',
    'assets/screen_savers/us/Remember your own faults.jpg',
    'assets/screen_savers/us/Righteousness Good Character.jpg',
    'assets/screen_savers/us/Silence is Wisdom.jpg',
    'assets/screen_savers/us/Sincerity.jpg',
    'assets/screen_savers/us/SoftWordsSoftenHearts.jpg',
    'assets/screen_savers/us/Speak a good word.jpg',
    'assets/screen_savers/us/Stranger in the world.jpg',
    'assets/screen_savers/us/Thanking is blessing.jpg',
    'assets/screen_savers/us/The more you care.jpg',
    'assets/screen_savers/us/TheClothforYourBurial.jpg',
    'assets/screen_savers/us/TheMoreYouKnowAllah.jpg',
    'assets/screen_savers/us/ThePeriodOfWaiting.jpg',
    'assets/screen_savers/us/TheTongue.jpg',
    'assets/screen_savers/us/TheWaytoParadise.JPG',
    'assets/screen_savers/us/ToFlatterToSalughter.JPG',
    'assets/screen_savers/us/Two things define you-1.jpg',
    'assets/screen_savers/us/Virtue of Deeds.jpg',
    'assets/screen_savers/us/WhenGodwishesHisServant.jpg',
    'assets/screen_savers/us/WhenYouDontKnow.JPG',
    'assets/screen_savers/us/WhenYouWakeUp.jpg',
    'assets/screen_savers/us/Whisper.JPG',
    'assets/screen_savers/us/WhoeverIsContent.jpg',
    'assets/screen_savers/us/Wisdom.jpg',
    'assets/screen_savers/us/World is Moment.jpg',
    'assets/screen_savers/us/Ya Allah Correct My Heart.jpg',
    'assets/screen_savers/us/YouShouldNeverIncrease.jpg',
    'assets/screen_savers/us/Your words.jpg',
    'assets/screen_savers/us/YourBreath.jpg',
    'assets/screen_savers/us/a-busy-life-makes.jpg',
    'assets/screen_savers/us/a-moment-of-patience.jpg',
    'assets/screen_savers/us/be-careful-with-your.jpg',
    'assets/screen_savers/us/be-somebody-in-the.jpg',
    'assets/screen_savers/us/before-you-say-something.jpg',
    'assets/screen_savers/us/believe in God.jpg',
    'assets/screen_savers/us/butterfly_wood-HD text.jpg',
    'assets/screen_savers/us/changing ourselves.jpg',
    'assets/screen_savers/us/company defines you.jpg',
    'assets/screen_savers/us/counting others sins.jpg',
    'assets/screen_savers/us/do-not-mock.jpg',
    'assets/screen_savers/us/dont wait.jpg',
    'assets/screen_savers/us/dont-forget-someone.jpg',
    'assets/screen_savers/us/fall-wide.jpg',
    'assets/screen_savers/us/good-deeds-shouldbe.jpg',
    'assets/screen_savers/us/green_wall_window.jpg',
    'assets/screen_savers/us/guide us to speak the best.jpg',
    'assets/screen_savers/us/if you want god to love-1.jpg',
    'assets/screen_savers/us/if-you-cant-be.jpg',
    'assets/screen_savers/us/if-you-live-for.jpg',
    'assets/screen_savers/us/imagine-slleping.jpg',
    'assets/screen_savers/us/instead-of-bashing.jpg',
    'assets/screen_savers/us/intent to understand.jpg',
    'assets/screen_savers/us/mention-allah-in-a-gathering.jpg',
    'assets/screen_savers/us/noone is looking.jpg',
    'assets/screen_savers/us/pink_keep busy.jpg',
    'assets/screen_savers/us/poppy_flowers-buda.jpg',
    'assets/screen_savers/us/pray-to-have.jpg',
    'assets/screen_savers/us/romatic_nature-worded.jpg',
    'assets/screen_savers/us/sign of beautiful person.jpg',
    'assets/screen_savers/us/smiling.jpg',
    'assets/screen_savers/us/stop-focusing-on.jpg',
    'assets/screen_savers/us/the-only-thing-worth.jpg',
    'assets/screen_savers/us/the-tears-of-a-sinner.jpg',
    'assets/screen_savers/us/there-is-no-gift.jpg',
    'assets/screen_savers/us/when-you-become.jpg',
    'assets/screen_savers/us/whenever-you-are-alone.jpg',
    'assets/screen_savers/us/whoever-believes.jpg',
    'assets/screen_savers/us/ya-rab-dont-put.jpg',
    'assets/screen_savers/us/you-can--preach.jpg',
    'assets/screen_savers/us/you-owe-your-parents.jpg',
  ];
}
